package dev.yidafu.swc.e2e

import dev.yidafu.swc.SwcNative
import dev.yidafu.swc.SwcJson
import dev.yidafu.swc.generated.*
import dev.yidafu.swc.generated.dsl.* // ktlint-disable no-wildcard-imports
import io.kotest.core.spec.style.ShouldSpec
import io.kotest.matchers.shouldBe
import java.io.InputStream

/**
 * E2E tests for printSync method - comparing printed code from Kotlin and @swc/core
 * * Test flow:
 * 1. Read pre-generated AST JSON from resources/print directory (generated by generate-print-resources.js)
 * 2. Parse AST JSON to Program object using parseAstTree
 * 3. Use Kotlin SwcNative#printSync to print AST JSON to code
 * 4. Compare with pre-generated code from @swc/core (normalized)
 * * Covers: ts, js, tsx, jsx file types
 */
class AstJsonPrintE2ETest : ShouldSpec({
    val swcNative = SwcNative()

    /**
     * Read pre-generated AST JSON from resources directory
     * These files are generated by generate-print-resources.js script using @swc/core
     */
    fun readAstJson(resourceName: String): String {
        val resourcePath = "print/$resourceName.json"
        val inputStream: InputStream = AstJsonPrintE2ETest::class.java.classLoader
            .getResourceAsStream(resourcePath)
            ?: throw IllegalStateException("Cannot find resource: $resourcePath")

        return inputStream.bufferedReader().use { it.readText() }
    }

    /**
     * Read pre-generated print result code from resources directory
     * These files are generated by generate-print-resources.js script using @swc/core
     */
    fun readPrintResult(resourceName: String): String {
        val resourcePath = "print/$resourceName.js"
        val inputStream: InputStream = AstJsonPrintE2ETest::class.java.classLoader
            .getResourceAsStream(resourcePath)
            ?: throw IllegalStateException("Cannot find resource: $resourcePath")

        return inputStream.bufferedReader().use { it.readText() }
    }

    /**
     * Normalize code for comparison by:
     * - Normalizing line endings
     * - Trimming whitespace
     * - Removing empty lines
     */
    fun normalizeCode(code: String): String {
        return code
            .replace("\r\n", "\n")
            .replace("\r", "\n")
            .lines()
            .map { it.trim() }
            .filter { it.isNotEmpty() }
            .joinToString("\n")
            .trim()
    }

    fun testPrint(
        resourceName: String,
        printOptions: Options,
        testName: String
    ) {
        // 1. Read pre-generated AST JSON from resources
        val astJsonStr = readAstJson(resourceName)

        // 2. Parse AST JSON to Program object
        val program = SwcJson.parseAstTree(astJsonStr)

        // 3. Use Kotlin SwcNative#printSync to print AST JSON to code
        val kotlinPrintedOutput = swcNative.printSync(program, printOptions)
        val kotlinPrintedCode = kotlinPrintedOutput.code

        // 4. Read pre-generated @swc/core print result (reference)
        val swcPrintedCode = readPrintResult(resourceName)

        // 5. Normalize and compare
        val normalizedSwcCode = normalizeCode(swcPrintedCode)
        val normalizedKotlinCode = normalizeCode(kotlinPrintedCode)

        if (normalizedSwcCode != normalizedKotlinCode) {
            println("Test failed: $testName")
            println("SWC printed code:")
            println(swcPrintedCode)
            println("\nKotlin printed code:")
            println(kotlinPrintedCode)
            println("\nNormalized SWC code:")
            println(normalizedSwcCode)
            println("\nNormalized Kotlin code:")
            println(normalizedKotlinCode)
        }

        normalizedKotlinCode shouldBe normalizedSwcCode
    }

    should("printSync JavaScript code") {
        testPrint(
            resourceName = "javascript-function",
            printOptions = options { },
            testName = "JavaScript print"
        )
    }

    should("printSync TypeScript code") {
        testPrint(
            resourceName = "typescript-interface",
            printOptions = options { },
            testName = "TypeScript print"
        )
    }

    should("printSync TSX code") {
        testPrint(
            resourceName = "tsx-component",
            printOptions = options { },
            testName = "TSX print"
        )
    }

    should("printSync JSX code") {
        testPrint(
            resourceName = "jsx-component",
            printOptions = options { },
            testName = "JSX print"
        )
    }

    should("printSync JavaScript with ES6 features") {
        testPrint(
            resourceName = "javascript-es6-features",
            printOptions = options { },
            testName = "JavaScript ES6 features print"
        )
    }

    should("printSync TypeScript with generics") {
        testPrint(
            resourceName = "typescript-generics",
            printOptions = options { },
            testName = "TypeScript generics print"
        )
    }

    should("printSync with minify option") {
        testPrint(
            resourceName = "javascript-with-minify",
            printOptions = options {
                minify = true
            },
            testName = "JavaScript print with minify"
        )
    }

    should("printSync with target option") {
        testPrint(
            resourceName = "javascript-with-target",
            printOptions = options {
                jsc = JscConfig().apply {
                    target = JscTarget.ES2020
                }
            },
            testName = "JavaScript print with ES2020 target"
        )
    }

    should("printSync module with imports") {
        testPrint(
            resourceName = "module-with-imports",
            printOptions = options { },
            testName = "Module with imports print"
        )
    }

    should("printSync JavaScript with simple import") {
        testPrint(
            resourceName = "javascript-simple-import",
            printOptions = options { },
            testName = "JavaScript simple import print"
        )
    }

    should("printSync compiled module code") {
        testPrint(
            resourceName = "javascript-compiled-module",
            printOptions = options { },
            testName = "JavaScript compiled module print"
        )
    }
})
