/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 *
 * Detailed information about configuring a multi-project build in Gradle can be found
 * in the user manual at https://docs.gradle.org/8.0.2/userguide/multi_project_builds.html
 * This project uses @Incubating APIs which are subject to change.
 */

pluginManagement {
    repositories {
        maven("https://repo.huaweicloud.com/repository/maven/")
        maven("https://mirrors.cloud.tencent.com/nexus/repository/maven-public")
        maven("https://s01.oss.sonatype.org/content/groups/public/")
        gradlePluginPortal()
        mavenCentral()
    }
}

enableFeaturePreview("TYPESAFE_PROJECT_ACCESSORS")

dependencyResolutionManagement {
    repositories {
        maven("https://repo.huaweicloud.com/repository/maven/")
        maven("https://mirrors.cloud.tencent.com/nexus/repository/maven-public")
        maven("https://s01.oss.sonatype.org/content/groups/public/")
        mavenCentral()
    }
    
    versionCatalogs {
        create("libs") {
            from(files("./build-plugin/libs.versions.toml"))
        }
    }
}

includeBuild("build-plugin")

rootProject.name = "swc-bing"

include("swc-binding")
project(":swc-binding").name = "swc-binding"

include("swc-generator")
project(":swc-generator").name = "swc-generator"
