name: 🐛 Bug Report
description: Report a bug or unexpected behavior
title: "[Bug] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please fill out the form below.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the bug is
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Create SwcNative instance
        2. Call parseSync with...
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: The code should...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: Instead, I got...
    validations:
      required: true

  - type: textarea
    id: code
    attributes:
      label: Code Example
      description: A minimal code example that reproduces the issue
      render: kotlin
      placeholder: |
        ```kotlin
        val swc = SwcNative()
        // Your code here
        ```
    validations:
      required: true

  - type: textarea
    id: error
    attributes:
      label: Error Message / Stack Trace
      description: If applicable, paste the error message or stack trace
      render: text
      placeholder: |
        Exception in thread "main" java.lang.RuntimeException: ...

  - type: dropdown
    id: module
    attributes:
      label: Affected Module
      description: Which module is affected?
      options:
        - swc-binding
        - swc-generator
        - swc-jni
        - Documentation
        - Other
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version
      description: swc-binding version (e.g., 0.7.0)
      placeholder: 0.7.0
    validations:
      required: true

  - type: input
    id: kotlin_version
    attributes:
      label: Kotlin Version
      description: Kotlin version (e.g., 2.2.10)
      placeholder: 2.2.10

  - type: input
    id: jvm_version
    attributes:
      label: JVM Version
      description: Java version (e.g., 17)
      placeholder: 17

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - Linux
        - macOS
        - Windows
        - Other
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context, screenshots, or information about the problem
      placeholder: Add any other context about the problem here...

