name: ✨ Feature Request
description: Suggest a new feature or enhancement
title: "[Feature] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please fill out the form below.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: I would like to see...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered
      placeholder: Other approaches I've thought about...

  - type: dropdown
    id: module
    attributes:
      label: Affected Module
      description: Which module would this feature affect?
      options:
        - swc-binding
        - swc-generator
        - swc-jni
        - Documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: api
    attributes:
      label: Proposed API
      description: If applicable, describe the proposed API or interface
      render: kotlin
      placeholder: |
        ```kotlin
        // Proposed API example
        swc.newMethod(...)
        ```

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would be helpful
        - High - Important for my use case
        - Critical - Blocking my project
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context, examples, or mockups about the feature request
      placeholder: Add any other context or screenshots about the feature request here...

